version: '3'

services:
  server:
    container_name: NODEJS_SERVER
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'

  db:
    image: 'mongo'
    container_name: mongodatabase
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

