FROM node:16

WORKDIR /assignmentcrud

#COPY . .

COPY package*.json ./

RUN npm install

COPY src ./src

COPY tsconfig.json ./

RUN npm run build

RUN chmod +x ./src/wait-for.sh

EXPOSE 8080

CMD ["./src/wait-for.sh", "host.docker.internal:27017", "-- node", "/dist/index.js"]