FROM node:16

WORKDIR /assignmentcrud

#COPY . .

COPY package*.json ./

RUN npm install

COPY src ./src

COPY tsconfig.json ./

#COPY tsconfig.json ./

RUN npm run build

EXPOSE 8080

RUN chmod +x ./src/wait-for-it.sh

CMD ["node", "dist/index.js"]